# Generated by Django 5.2.6 on 2025-09-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='é_resposta',
            field=models.BooleanField(default=False),
        ),
    ]
