# Generated by Django 5.2.6 on 2025-09-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_mensagem_é_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
