# Generated by Django 4.2.24 on 2025-09-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_mensagem_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='nome_grupo',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='grupo',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='grupo_perfis/'),
        ),
    ]
