# Generated by Django 4.2.24 on 2025-09-13 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_nome_grupo_grupo_nome_grupo_imagem_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='autor_e_hora',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='usuarios.grupo'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
