# Generated by Django 4.2.24 on 2025-09-13 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_mensagem_autor_e_hora_alter_mensagem_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='usa_ia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
